spring.application.name=spring-security-jwt
api.key=e4317915c71fe072a930dfdef4155060
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://localhost:3306/security
spring.datasource.username= root
spring.datasource.password= pritiswami@123
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery= SELECT 1
spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.main.allow-circular-references=true
server.port=4545


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pritinswami@gmail.com
spring.mail.password=mkamsiotbpyopolz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
